### ISSUE TITLE
Job State Refactor

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#338]
We're working through a major refactor of the Job and Payload workflows. Here's the remaining work: 
- [x] ConditionMachineOf feature works as expected (#287) (bcwaldon)
- [x] Index payloads by hash in etcd (#325) (jonboulle)
- [x] Ensure we didn't lose any short-name flags (#333) (jonboulle)
- [x] Engine rather than fleetctl should drive job transitions between inactive <--> launched (bcwaldon)
- [x] Doing a rolling upgrade of a fleet cluster from v0.2.0 to this new code must work "well"
- [x] Document all of the changes made
