### ISSUE TITLE
Resource Management Phase I

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#601]
- [x] track total & consumed memory - #622
- [x] track scheduled unit count - #616
- [x] cache resource usage in Engine - #622 
- [x] use resource data to schedule resource-bounded jobs, bypassing offering - #647 
- [X] drop offering, schedule based on # of units - #728
- [ ] consult available resources when scheduling - #678 
- [ ] make host resources configurable
