### ISSUE TITLE
Supporting changes to prepare for global units

### ISSUE THREAD

**Issue by jonboulle** [coreos/fleet#679]
- [x] publish `UnitHash` in `UnitState` - #700 
- [x] publish `UnitState` scoped by machine (with backwards compatibility) - #638 
- [x] add `list-unit-files` to track desired state of all units known by fleet - #688 
- [x] modify registry APIs to facilitate accessing multiple `UnitState`s
- [x] modify `list-units` to report only actual unit state reported by systemd (remove `TSTATE`) - #756
- [x] clarify `list-units`/`list-unit-files` distinction in documentation - #756 

Actual "global units" work will be tracked in #681
